USE QUEENSWOOD_SUMMER_CAMP

CREATE TABLE EMPLOYEE (
EmployeeID INT PRIMARY KEY
, Name VARCHAR(100) NOT NULL
, Email VARCHAR(120) NOT NULL UNIQUE
, Phone VARCHAR(20) NOT NULL
, Position VARCHAR(30) NOT NULL
, Salary DECIMAL(8,2) NOT NULL CHECK (Salary > 0)
, ActivitiesBonus DECIMAL(8,2) NOT NULL DEFAULT 0 CHECK (ActivitiesBonus >= 0)
, TutorBonus DECIMAL(8,2) NOT NULL DEFAULT 0 
, CHECK (TutorBonus >= 0)
, CHECK (Position IN ('Coach', 'Tutor', 'Monitor', 'Admin', 'Manager', 'Cook'))
)

CREATE TABLE CABIN (
CabinID INT PRIMARY KEY
, Name VARCHAR(80) NOT NULL
, Type CHAR(1) NOT NULL
, Spots INT NOT NULL
, EmployeeID INT NOT NULL
, CHECK (Type IN ('M', 'F'))
, CHECK (Spots BETWEEN 3 AND 6)
, FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
)

CREATE TABLE CHILD (
ChildID INT PRIMARY KEY
, Name VARCHAR(100) NOT NULL
, Gender CHAR(1) NOT NULL
, DateOfBirth DATE NOT NULL
, CabinID INT NULL
, CHECK (Gender IN ('M', 'F'))
, FOREIGN KEY (CabinID) REFERENCES CABIN(CabinID)
)

CREATE TABLE PARENT (
ParentID INT PRIMARY KEY
, Name VARCHAR(80) NOT NULL
, Surnames VARCHAR(120) NOT NULL
, Gender CHAR(1) NOT NULL
, Phone VARCHAR(20) NOT NULL
, CHECK (Gender IN ('M', 'F'))
)

CREATE TABLE HAS_PARENT (
ChildID INT NOT NULL
, ParentID INT NOT NULL
, PRIMARY KEY (ChildID, ParentID)
, FOREIGN KEY (ChildID) REFERENCES CHILD(ChildID)
, FOREIGN KEY (ParentID) REFERENCES PARENT(ParentID)
)

CREATE TABLE MEDICAL_ISSUE (
ChildID INT NOT NULL
, Number INT NOT NULL
, Medication VARCHAR(150)
, SpecialNeeds VARCHAR(200)
, IssueDescription VARCHAR(250) NOT NULL
, PRIMARY KEY (ChildID, Number)
, CHECK (Number >= 1)
, FOREIGN KEY (ChildID) REFERENCES CHILD(ChildID)
)

CREATE TABLE ACTIVITY (
ActivityID INT PRIMARY KEY
, Name VARCHAR(100) NOT NULL
, Description VARCHAR(250)
, Days VARCHAR(15) NOT NULL
, TimeSlot VARCHAR(20) NOT NULL
, Type VARCHAR(20) NOT NULL
, AvailableSpots INT NOT NULL
, CHECK (Days IN ('Mon-Wed-Fri', 'Tue-Thu-Sat'))
, CHECK (TimeSlot IN ('10:00-12:00', '16:00-18:00', '19:00-21:00'))
, CHECK (Type IN ('Physical', 'Recreational'))
, CHECK (AvailableSpots BETWEEN 10 AND 25)
)

CREATE TABLE REGISTER (
ChildID INT NOT NULL
, ActivityID INT NOT NULL
, PRIMARY KEY (ChildID, ActivityID)
, FOREIGN KEY (ChildID) REFERENCES CHILD(ChildID)
, FOREIGN KEY (ActivityID) REFERENCES ACTIVITY(ActivityID)
)

CREATE TABLE IN_CHARGE (
EmployeeID INT NOT NULL
, ActivityID INT NOT NULL
, Bonus DECIMAL(6,2) NOT NULL DEFAULT 50
, PRIMARY KEY (EmployeeID, ActivityID)
, CHECK (Bonus = 50)
, FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
, FOREIGN KEY (ActivityID) REFERENCES ACTIVITY(ActivityID)
)
